# These substitutions allow the end user to override certain values
substitutions:
  name: "onioff-switch"
  friendly_name: "ONiOFF Switch"

  device_type: "switch"
  device_name: "Switch"
  restore_mode: "ALWAYS_OFF"

esphome:
  project:
    project_name: "onioff-switch"
    project_version: 0.9.0

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://esphome/esphome-onioff-smart-switch/onioff-switch.yaml@main

packages:
  device-base: !include
    file: common/project-base.yaml
    vars:
      name: ${name}
      friendly_name: ${friendly_name}

  onioff-base: !include
    file: common/onioff-base.yaml
    vars:
      device_name: ${device_name}
      device_type: ${device_type}
      restore_mode: ${restore_mode}
