# These substitutions allow the end user to override certain values
substitutions:
  name: "onioff-switch"
  friendly_name: "ONiOFF Switch"
  restore_mode: "ALWAYS_OFF"

esphome:
  project:
    name: cblumer.onioff-switch
    version: 0.9.2

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://esphome/esphome-onioff-smart-switch/onioff-switch.yaml@main

packages:
  device-base: !include
    file: common/project-base.yaml
    vars:
      name: ${name}
      friendly_name: ${friendly_name}

  onioff-base: !include
    file: common/onioff-base.yaml
    vars:
      device_name: Switch
      device_type: switch
      device_platform: output
      restore_mode: ${restore_mode}
