# These substitutions allow the end user to override certain values
substitutions:
  restore_mode: "ALWAYS_OFF"

esphome:
  name: "onioff-switch-fan"
  friendly_name: "ONiOFF Fan Switch"
  project:
    name: cblumer.onioff-switch-fan
    version: 0.9.3

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://esphome/esphome-onioff-smart-switch/onioff-fan.yaml@main

packages:
  onioff-base: !include
    file: common/onioff-base.yaml
    vars:
      device_name: Fan
      device_type: fan
      device_platform: binary
      restore_mode: ${restore_mode}
