name: Build and publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  switch:
    name: Build and publish generic switch template
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # Set the filenames of your config files here:
      files: onioff-switch.yaml
      # Set the name of your project here:
      name: ONiOFF Smart Switch
      # Don't clean other project files
      clean: false
      manifest_filename: onioff-switch-manifest.json
  light:
    name: Build and publish light switch template
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # Set the filenames of your config files here:
      files: onioff-light.yaml
      # Set the name of your project here:
      name: ONiOFF Smart Light Switch
      # Don't clean other project files
      clean: false
      manifest_filename: onioff-light-manifest.json
  fan:
    name: Build and publish fan switch template
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # Set the filenames of your config files here:
      files: onioff-fan.yaml
      # Set the name of your project here:
      name: ONiOFF Smart Fan Switch
      # Don't clean other project files
      clean: false
      manifest_filename: onioff-fan-manifest.json
