name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  switch:
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # Set the filenames of your config files here:
      files: onioff-switch.yaml
      # Set the name of your project here:
      name: ONiOFF Smart Switch
      # Don't clean other project files
      clean: true
      manifest_filename: onioff-light-manifest.json
  light:
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # Set the filenames of your config files here:
      files: onioff-light.yaml
      # Set the name of your project here:
      name: ONiOFF Smart Light Switch
      # Don't clean other project files
      clean: true
      manifest_filename: onioff-light-manifest.json
  fan:
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # Set the filenames of your config files here:
      files: onioff-fan.yaml
      # Set the name of your project here:
      name: ONiOFF Smart Fan Switch
      # Don't clean other project files
      clean: true
      manifest_filename: onioff-light-manifest.json
